### ISSUE TITLE
go mod support

### ISSUE THREAD

**Issue by pffs** [aybabtme/logzalgo#3]
The namespace for logrus in `zalgo_formatter.go` has a capital for Sirupsen, while the actual `github.com/sirupsen/logrus` does not. Go modules are case sensitive, which prevents this formatter from being used in a project with go modules enabled:

```
go: github.com/aybabtme/logzalgo imports
        github.com/Sirupsen/logrus: github.com/Sirupsen/logrus@v1.4.2: parsing go.mod:
        module declares its path as: github.com/sirupsen/logrus
                but was required as: github.com/Sirupsen/logrus
```

Should just require changing the casing on the one import, I can submit a PR to fix if you want.

**Comment by aybabtme** [comment]
Sure thing, send a PR and I'll merge it!
